# Generated by Django 4.2.15 on 2024-09-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_ingredients_alter_recipe_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pic',
        ),
        migrations.AddField(
            model_name='recipe',
            name='_difficulty',
            field=models.CharField(default='', max_length=120),
        ),
    ]
