# Generated by Django 4.2.15 on 2024-08-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.IntegerField(default=0, help_text='in min')),
                ('ingredients', models.CharField(help_text="Each ingredient seperated by a comma'", max_length=250, null=True)),
            ],
        ),
    ]
