# Generated by Django 4.2.15 on 2024-09-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(help_text="Each ingredient seperated by a comma, like 'Eggs, Butter'", max_length=250),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', help_text='Choose an image with minimum 250px width.', upload_to='recipes'),
        ),
    ]
